ARG docker_registry=docker.io/alnoda
ARG image_tag=2.2

FROM ${docker_registry}/notebook-workspace:${image_tag}

RUN echo "------------------------------------------------------ Nbconvert dependencies" \
    && apt-get install -y pandoc \
    && apt-get install -y texlive-xetex texlive-fonts-recommended texlive-plain-generic 

USER abc

# Jupyter extensions
RUN echo "------------------------------------------------------ BeakerX" \
    && /home/abc/miniconda3/bin/conda install -y -c conda-forge ipywidgets beakerx \
    && echo "------------------------------------------------------ Elyra" \
    && conda install -c conda-forge elyra[all] \
    && conda install -c conda-forge nbsafety
    && echo "------------------------------------------------------ Nbsafety" \
    && https://nbsafety.org/ 
    && echo "------------------------------------------------------ Jupyter-lsp" \
    pip install python-language-server
    && /home/abc/miniconda3/bin/conda install -y -c conda-forge jupyter-lsp-python \
    && echo "------------------------------------------------------ Tabnine" (no need if Jupyter LSP is installed) \
    && pip install jupyter-tabnine==1.2.3 \
    && jupyter nbextension install --py jupyter_tabnine \
    && jupyter nbextension enable jupyter_tabnine --py \
    && jupyter serverextension enable --py jupyter_tabnine
    

https://github.com/LineaLabs/lineapy#getting-started
https://nteract-scrapbook.readthedocs.io/en/latest/index.html

## Engineering Kedro
kedro==0.18.1
kedro-viz==4.6.0

# Compute
# https://github.com/ipython/ipyparallel
# https://github.com/modin-project/modin
https://github.com/pola-rs/polars
https://github.com/vaexio/vaex
https://github.com/fugue-project/fugue 

# Kernels
# https://github.com/jupyter/jupyter/wiki/Jupyter-kernels
# https://github.com/jupyter-xeus/xeus-python

# Data gathering
https://github.com/MartinHeinz/ga-extractor
https://docs.meltano.com/guide/installation
https://www.singer.io/

# Data exploration/profiling
https://github.com/finos/perspective/
https://github.com/mito-ds/monorepo 
https://github.com/ydataai/pandas-profiling
https://github.com/sfu-db/dataprep 
https://github.com/fbdesignpro/sweetviz
https://github.com/ing-bank/popmon
https://github.com/bluenote10/tabloo 
https://docs.bamboolib.8080labs.com/

# Plotting
https://plotly.com/python/getting-started/#jupyterlab-support
https://github.com/plotly/jupyter-dash
https://www.pygal.org/en/stable/ 
https://github.com/yhat/ggpy
https://github.com/bokeh/bokeh


# Vidgets
https://github.com/jupyter-widgets/ipyleaflet
https://github.com/bqplot/bqplot

# Reports
https://jupyter-flex.danielfrg.com/widgets-voila/
https://jupyter-flex.danielfrg.com/ 

# Productionalization
https://panel.holoviz.org/getting_started/index.html 
https://github.com/mljar/mercury
https://mljar.com/blog/how-to-use-jupyter-notebook/

# Tests
https://testbook.readthedocs.io/en/latest/index.html

# Other
https://github.com/jtpio/jupyterlab-theme-toggle # theme toggler
https://github.com/kenshohara/theme-nord-extension


# Tools
# https://pypi.org/project/jupyter-paperboy/
RUN echo "------------------------------------------------------ Jut" \
    && pipx install jut 



    
