ARG docker_registry=docker.io/alnoda
ARG image_tag=18.04-0.5

FROM ${docker_registry}/workspace-in-docker:${image_tag}

USER root

ENV PATH=$PATH:/opt/go/bin GOPATH=/home/project/

RUN cd /tmp && wget https://dl.google.com/go/go1.15.2.linux-amd64.tar.gz \
    && tar -C /opt -xzf go1.15.2.linux-amd64.tar.gz 

USER abc