ARG docker_registry=docker.io/alnoda
ARG image_tag=2.2

FROM ${docker_registry}/codeserver-workspace:${image_tag}
USER root

COPY examples/example /home/abc/example
COPY ./mkdocs/mkdocs.yml /home/docs/mkdocs.yml 

RUN apt-get -y update \
    && echo "------------------------------------------------------ java 8" \
    && sudo apt-get install -y openjdk-8-jre \
    && apt-get install -y openjdk-8-jdk \
    && echo "------------------------------------------------------ maven" \
    && wget https://dlcdn.apache.org/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz -P /tmp \
    && tar xf /tmp/apache-maven-3.8.5-bin.tar.gz \
    && mv apache-maven-3.8.5 /opt/maven \
    && rm /tmp/apache-maven-3.8.5-bin.tar.gz \
    && echo "------------------------------------------------------ gradle" \
    && wget https://services.gradle.org/distributions/gradle-7.4.2-bin.zip -P /tmp \
    && unzip -d /opt/gradle /tmp/gradle-7.4.2-bin.zip \
    && rm /tmp/gradle-7.4.2-bin.zip \
    && find /home -type d | xargs -I{} chown -R abc {} \
    && find /home -type f | xargs -I{} chown abc {} 
    
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/ \
    M2_HOME=/opt/maven \
    MAVEN_HOME=/opt/maven \
    PATH="/opt/maven/bin:${PATH}" 

ENV GRADLE_HOME=/opt/gradle/gradle-7.4.2 \
    PATH="/opt/gradle/gradle-7.4.2/bin:${PATH}"

USER abc



