FROM alnoda/theia-workspace:4.0

RUN sudo apt-get -y update \
    && echo "------------------------------------------------------ java 17" \
    && sudo apt-get install -y openjdk-17-jre \
    && sudo apt-get install -y openjdk-17-jdk \
    && echo "------------------------------------------------------ maven" \
    && cd /tmp && wget https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz -P /tmp \
    && tar xf /tmp/apache-maven-3.8.6-bin.tar.gz \
    && mv apache-maven-3.8.6 /home/abc/maven \
    && rm /tmp/apache-maven-3.8.6-bin.tar.gz \
    && echo "------------------------------------------------------ gradle" \
    && wget https://services.gradle.org/distributions/gradle-7.4.2-bin.zip -P /tmp \
    && unzip -d /home/abc/gradle /tmp/gradle-7.4.2-bin.zip \
    && rm /tmp/gradle-7.4.2-bin.zip 
    
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/ \
    M2_HOME=/home/abc/maven \
    MAVEN_HOME=/home/abc/maven \
    PATH="/home/abc/maven/bin:${PATH}" 

ENV GRADLE_HOME=/home/abc/gradle/gradle-7.4.2 \
    PATH="/home/abc/gradle/gradle-7.4.2/bin:${PATH}"

# Copy example into the workspace
COPY --chown=abc:abc example /home/abc/example

# Build Alnoda workspace
COPY --chown=abc:abc workspace /tmp/workspace
RUN pipx uninstall alnoda-wrk; pipx install alnoda-wrk; alnoda-wrk build /tmp/workspace && rm -rf /tmp/workspace