
# Query 
RUN wrk install pgadmin-4==6.21
RUN wrk install pgcli==3.5.0
RUN wrk install pspg
RUN wrk install octosql==0.12.2
RUN wrk install gobang==0.1.0

# Performance
RUN wrk install pgmetrics==1.12.0
RUN wrk install pgcenter==0.9.2

# Export / Import
RUN wrk install pg-dump
RUN wrk install pgclimb==0.3
RUN wrk install pgfutter==1.2

# Migration
RUN wrk install pgloader==0.0

# Data generation
RUN wrk install synth
RUN wrk install mock-data==3.0

# Change management
RUN wrk install migra==3.0.1
RUN wrk install sqitch
RUN wrk install yuniql==1.1.55
RUN wrk install tern==v2.1.1
RUN wrk install dbmate==2.5.0

# Query optimisation
RUN wrk install pev==0.24.0
RUN wrk install pg-flame==1.2

# Documentation
RUN wrk install tbls==1.54.2

# DB desing
RUN wrk install dbdesigner-id==0.0.1
RUN wrk install dbdesigner==0.1

# Job scheduler
RUN wrk install cronicle==0.9.10